### PR TITLE
use static linking in Dockerfile; add docker-compose.yml

### PR DESCRIPTION
**Pull request by Alistair1231**
Hi!
Great project! While I do like nix, I have all my server stuff managed using docker at the moment and want to keep it consistent. I had some issues with the included Dockerfile, as it kept giving me glibc errors.
To circumvent that, I just made it compile statically linked, and it seems to work now.

I also added a very basic docker-compose.yml, so people can just clone the repo and use `docker compose up -d` to get everything up and running.

### CODE REVIEW

**Comment by w4** [comment]
thanks!

**Comment by rothgar** [comment]
Is statically linking against `x86_64-unknown-linux-musl` but using debian (glibc based) a problem?

**Comment by Alistair1231** [comment]
> Is statically linking against `x86_64-unknown-linux-musl` but using debian (glibc based) a problem?

Not sure, it seems to work fine. Though, since it only copies the executable, the base image should be able to be changed to anything else. I assume that the issue came, due to the glibc version in rust:1-slim and debian:bullseye-slim being different. i.e. the one used to compile being newer than the one it ran on.

Instead of having this 2 phase approach, the executable could probably also just be run in the rust:1-slim based container. 

I personally am happy with how it is now, as it seems to work, which is the main thing for me.

**Comment by rothgar** [comment]
If it's statically compiled do you need a distro at all? I'm assuming `FROM scratch` would work, but I haven't tested it.

**Comment by Alistair1231** [comment]
> If it's statically compiled do you need a distro at all? I'm assuming `FROM scratch` would work, but I haven't tested it.

I've never used from scratch and wasn't even aware it's a thing. But alpine is pretty lightweight with 5 MiB, so not a lot is lost by using it.

**Comment by w4** [comment]
Moved to `FROM scratch` in https://github.com/w4/bin/commit/c2678219d8e8fcd826763b6a0485f53171bf6da2

**Pull request merged**
